name: Atualiza_simples_com_cache_renv

on:
  schedule:
    # Verificações frequentes à hora da publicação dos dados (OMIE ~12h Lisboa)
    # → Corresponde a:
    #    - 10:00–11:59 hora de Lisboa no inverno (UTC+0)
    #    - 11:00–12:59 hora de Lisboa no verão (UTC+1)
    - cron: '*/6 10-11 * * *'  # 10:00–12:59 UTC

    # Verificações ao final do dia (ex: validação, dados em atraso)
    # → Corresponde a:
    #    - 17:00–18:59 hora de Lisboa no inverno (UTC+0)
    #    - 18:00–19:59 hora de Lisboa no verão (UTC+1)
    - cron: '*/6 17-18 * * *'  # 18:00–19:59 UTC

  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache APT packages
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: |
            xvfb
            openjdk-11-jre-headless
            libcurl4-openssl-dev
            libssl-dev
            libxml2-dev
            wget
            libdbus-glib-1-2
            net-tools
            cmake
            libx11-dev
            pandoc
            gdebi-core
            qpdf
            devscripts
            ghostscript
          version: 1

      - name: Instalar dependências (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            xvfb \
            openjdk-11-jre-headless \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            wget \
            libdbus-glib-1-2 \
            net-tools \
            cmake \
            libx11-dev \
            pandoc \
            gdebi-core \
            qpdf \
            devscripts \
            ghostscript

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.3'

      - name: Setup renv (com cache automático)
        uses: r-lib/actions/setup-renv@v2

      - name: Executar script R
        run: |
          Rscript -e '
            renv::activate();
            source("gs/script_teste4.R")
          '

      - name: Verificar existência do CSV
        run: |
          if [ ! -f "gs/SimuladorEletricidade_OF_MN_2025_2.csv" ]; then
            echo "::error::CSV file does not exist. Skipping commit."
            exit 1
          fi
          echo "CSV file exists. Proceeding to commit."

      - name: Commit novo ficheiro
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            gs/SimuladorEletricidade_OF_MN_2025_3.csv
            gs/grafico_omie_plotly.html
            gs/simulador.json
            gs/simulador.json.gz
            gs/Precos_20100101_hoje.parquet
          message: "Adiciona novo arquivo gerado pelo workflow"
          github_token: ${{ secrets.PAT_TOKEN }}
