name: Run R Script and Commit CSV

on:
  schedule:
    - cron: '0 14,20 * * *'  # Executa às 14h e 20h UTC todos os dias
  workflow_dispatch:  # Permite executar manualmente

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2

      - name: Setup cache for R packages
        uses: actions/cache@v3
        with:
          path: renv/cache
          key: renv-${{ runner.os }}-${{ hashFiles('renv.lock') }}
          restore-keys: renv-${{ runner.os }}-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install and activate renv
        run: |
          Rscript -e 'install.packages("renv", repos="https://cran.rstudio.com/")'
          Rscript -e 'renv::restore(prompt = FALSE)'

      - name: Verify installed packages
        run: |
          Rscript -e 'installed.packages()[,1]'  # Lista pacotes instalados para debugging
          Rscript -e 'library(httr)'  # Testa se httr pode ser carregado

      - name: Run R script
        run: |
          cd gs
          Rscript rscript.R

      - name: Commit new file
        uses: EndBug/add-and-commit@v9
        with:
          add: "gs/SimuladorEletricidade_OF_MN_2025_2.csv"
          message: "Adiciona novo arquivo gerado pelo workflow"
          github_token: ${{ secrets.PAT_TOKEN }}
