name: Atualiza_novo_com_cache_renv

on:
  workflow_dispatch:

jobs:
  selenium-stable-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar dependências (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb openjdk-11-jre-headless libcurl4-openssl-dev libssl-dev libxml2-dev wget libdbus-glib-1-2 net-tools

      - name: Instalar Firefox ESR (versão estável)
        run: |
          wget -O firefox-esr.tar.bz2 "https://ftp.mozilla.org/pub/firefox/releases/115.8.0esr/linux-x86_64/en-US/firefox-115.8.0esr.tar.bz2"
          sudo tar xjf firefox-esr.tar.bz2 -C /opt
          sudo ln -sf /opt/firefox/firefox /usr/bin/firefox
          firefox --version

      - name: Instalar Geckodriver (compatível com Firefox ESR)
        run: |
          wget -q -O geckodriver.tar.gz "https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz"
          sudo tar -xzf geckodriver.tar.gz -C /usr/local/bin
          sudo chmod +x /usr/local/bin/geckodriver
          geckodriver --version

      - name: Baixar Selenium Server 3.141.59 (estável)
        run: |
          wget -O selenium-server.jar "https://github.com/SeleniumHQ/selenium/releases/download/selenium-3.141.59/selenium-server-standalone-3.141.59.jar"

      - name: Iniciar Xvfb e Selenium Server (versão estável definitiva)
        run: |
          sudo pkill Xvfb || true
          sudo rm -rf /tmp/.X99-lock /tmp/.X11-unix/X99
          Xvfb :99 -screen 0 1280x1024x24 &
          sleep 5
          echo "DISPLAY=:99" >> $GITHUB_ENV

          sudo pkill -f selenium-server || true
          nohup java \
            -Dwebdriver.gecko.driver=/usr/local/bin/geckodriver \
            -jar selenium-server.jar \
            -host 127.0.0.1 \
            -port 4444 \
            > selenium.log 2>&1 &

          sleep 15
          netstat -tuln | grep '127.0.0.1:4444' || (cat selenium.log && exit 1)

      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'

      - name: Cache renv packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/R/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Restaurar dependências com renv
        run: |
          Rscript -e 'install.packages("renv", repos="https://cloud.r-project.org")'
          Rscript -e 'renv::activate(); renv::restore(prompt = FALSE)'

      - name: Run R script
        env:
          DISPLAY: :99
        run: |
          Rscript -e '
            renv::activate();
            source("gs/rscript_teste.R")
          '

      - name: Check if CSV file exists
        run: |
          if [ ! -f "gs/SimuladorEletricidade_OF_MN_2025_2.csv" ]; then
            echo "::error::CSV file does not exist. Skipping commit."
            exit 1
          fi
          echo "CSV file exists. Proceeding to commit."

      # - name: Commit new file
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     add: "gs/SimuladorEletricidade_OF_MN_2025_3.csv"
      #     message: "Adiciona novo arquivo gerado pelo workflow"
      #     github_token: ${{ secrets.PAT_TOKEN }}

      - name: Exibir log Selenium Server (sempre)
        if: always()
        run: cat selenium.log
