name: Run R Script and Cache renv

on:
  schedule:
    - cron: '0 14,20 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libxml2-dev libssl-dev libx11-dev

      - name: Restore R package cache
        uses: actions/cache@v3
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Install R packages with renv
        run: |
          Rscript -e 'install.packages("renv", repos="https://cran.rstudio.com/")'
          Rscript -e 'renv::restore(prompt = FALSE)'

      - name: Run R script
        run: |
          Rscript -e 'source("renv/activate.R")'
          cd gs
          Rscript rscript.R
          
      - name: Commit new file
        uses: EndBug/add-and-commit@v9
        with:
          add: "gs/SimuladorEletricidade_OF_MN_2025_2.csv"
          message: "Adiciona novo arquivo gerado pelo workflow"
          github_token: ${{ secrets.PAT_TOKEN }}

