name: Run R Script and Commit CSV

on:
  schedule:
    - cron: '0 14,20 * * *'  # Executa às 14h e 20h UTC todos os dias
  workflow_dispatch:  # Permite execução manual

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2

      - name: Setup cache for R packages
        uses: actions/cache@v3
        with:
          path: renv/cache
          key: renv-${{ runner.os }}-${{ hashFiles('renv.lock') }}
          restore-keys: renv-${{ runner.os }}-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install renv and restore packages
        run: |
          Rscript -e 'install.packages("renv", repos="https://cran.rstudio.com/")'
          Rscript -e 'renv::restore(prompt = FALSE)'

      - name: Debug R Libraries (Antes da ativação do renv)
        run: |
          echo "### Caminhos de bibliotecas antes do renv:"
          Rscript -e '.libPaths()'
          echo "### Pacotes instalados antes do renv:"
          Rscript -e 'installed.packages()[,1]'

      - name: Activate renv
        run: |
          Rscript -e 'source("renv/activate.R")'

      - name: Debug R Libraries (Depois da ativação do renv)
        run: |
          echo "### Caminhos de bibliotecas após ativação do renv:"
          Rscript -e '.libPaths()'
          echo "### Pacotes instalados após ativação do renv:"
          Rscript -e 'installed.packages()[,1]'
          echo "### Status do renv:"
          Rscript -e 'renv::status()'

      - name: Force Set R Library Path
        run: |
          Rscript -e '.libPaths(c("/home/runner/work/_temp/Library", .libPaths()))'
          Rscript -e 'source("renv/activate.R")'
          Rscript -e 'library(httr)'

      - name: Run R script
        run: |
          cd gs
          Rscript rscript.R

      - name: Commit new file
        uses: EndBug/add-and-commit@v9
        with:
          add: "gs/SimuladorEletricidade_OF_MN_2025_2.csv"
          message: "Adiciona novo arquivo gerado pelo workflow"
          github_token: ${{ secrets.PAT_TOKEN }}
