name: Atualiza_simples_com_cache_renv

on:
  schedule:
    # Verificações frequentes à hora da publicação dos dados (OMIE ~12h Lisboa)
    # → Corresponde a:
    #    - 10:00–12:59 hora de Lisboa no inverno (UTC+0)
    #    - 11:00–13:59 hora de Lisboa no verão (UTC+1)
    - cron: '*/6 10-12 * * *'  # 10:00–12:59 UTC

    # Verificações ao final do dia (ex: validação, dados em atraso)
    # → Corresponde a:
    #    - 18:00–19:59 hora de Lisboa no inverno (UTC+0)
    #    - 19:00–20:59 hora de Lisboa no verão (UTC+1)
    - cron: '*/6 18-19 * * *'  # 18:00–19:59 UTC

  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar dependências (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb openjdk-11-jre-headless libcurl4-openssl-dev libssl-dev libxml2-dev wget libdbus-glib-1-2 net-tools

      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'

      - name: Cache renv packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/R/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Restaurar dependências com renv
        run: |
          Rscript -e 'install.packages("renv", repos="https://cloud.r-project.org")'
          Rscript -e 'renv::activate(); renv::restore(prompt = FALSE)'

      - name: Run R script
        run: |
          Rscript -e '
            renv::activate();
            source("gs/rscript_teste3.R")
          '

      - name: Check if CSV file exists
        run: |
          if [ ! -f "gs/SimuladorEletricidade_OF_MN_2025_2.csv" ]; then
            echo "::error::CSV file does not exist. Skipping commit."
            exit 1
          fi
          echo "CSV file exists. Proceeding to commit."

      - name: Commit new file
        uses: EndBug/add-and-commit@v9
        with:
          add: "gs/SimuladorEletricidade_OF_MN_2025_3.csv"
          message: "Adiciona novo arquivo gerado pelo workflow"
          github_token: ${{ secrets.PAT_TOKEN }}
