name: Run R Script and Commit CSV Teste

on:
  workflow_dispatch:  # Permite execução manual

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      RENV_PATHS_CACHE: ~/.local/share/renv/cache  # Define o caminho do cache do renv
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2

      - name: Create renv directory if it doesn't exist
        run: mkdir -p renv/library

      - name: Setup cache for R packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/share/renv/cache
            renv/library
          key: renv-cache-${{ runner.os }}-${{ hashFiles('renv.lock') }}
          restore-keys: |
            renv-cache-${{ runner.os }}-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libgit2-dev libx11-dev

      - name: Install renv, restore
        run: |
          Rscript -e 'install.packages("renv", repos="https://cran.rstudio.com/")'
          Rscript -e 'renv::activate(); renv::restore(prompt = FALSE)'

      - name: Debug R Libraries (Antes da ativação do renv)
        run: |
          echo "### Caminhos de bibliotecas antes do renv:"
          Rscript -e 'print(.libPaths())'
          echo "### Pacotes instalados antes do renv:"
          Rscript -e 'print(installed.packages()[,1])'

      - name: Debug R Libraries (Depois da ativação do renv)
        run: |
          echo "### Caminhos de bibliotecas após ativação do renv:"
          Rscript -e 'print(.libPaths())'
          echo "### Pacotes instalados após ativação do renv:"
          Rscript -e 'print(installed.packages()[,1])'
          echo "### Status do renv:"
          Rscript -e 'renv::status()'

      - name: Install Java
        run: sudo apt-get install -y default-jre

      - name: Download Selenium Server
        run: |
          wget https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.29.0/selenium-server-4.29.0.jar
          mv selenium-server-4.29.0.jar selenium-server.jar

      - name: Remove Firefox Snap
        run: |
          sudo snap remove firefox

      - name: Install Firefox and Geckodriver
        run: |
          sudo add-apt-repository ppa:mozillateam/ppa
          sudo apt-get update
          sudo apt-get install -y firefox
          GECKO_VERSION="0.36.0"
          wget -q "https://github.com/mozilla/geckodriver/releases/download/v$GECKO_VERSION/geckodriver-v$GECKO_VERSION-linux64.tar.gz"
          tar -xzf geckodriver-v$GECKO_VERSION-linux64.tar.gz
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/
          geckodriver --version

      - name: Kill any running Firefox
        run: |
          echo "🔪 Encerrando possíveis instâncias travadas do Firefox..."
          pkill -9 firefox || echo "Nenhuma instância do Firefox em execução."

      - name: Setup Virtual Display
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          echo "🎥 Display virtual iniciado."

      - name: Start Selenium Server
        run: |
          export DISPLAY=:99
          export PATH=$PWD:$PATH
          export GECKODRIVER_PATH="/usr/local/bin/geckodriver"
          
          echo "🔥 Iniciando Selenium Server..."
          java -Dwebdriver.gecko.driver=$GECKODRIVER_PATH \
               -jar selenium-server.jar standalone \
               --port 4444 --host 127.0.0.1 > selenium.log 2>&1 &
          
          sleep 30
          echo "✅ Selenium Server iniciado na porta 4444"

      - name: Check if Selenium port is open
        run: |
          echo "🔍 Verificando portas ativas..."
          if ! netstat -tuln | grep 4444; then
            echo "❌ ERRO: A porta 4444 não está ativa!"
            exit 1
          fi

      - name: Run R script
        run: |
          Rscript -e '
            renv::activate();
            print(.libPaths());
            library(httr);
            print(installed.packages()[,1]);
            print(Sys.getenv("RENV_PATHS_ROOT"));
            source("gs/rscript_teste.R")
          '

      - name: Check if CSV file exists
        run: |
          if [ ! -f "gs/SimuladorEletricidade_OF_MN_2025_3.csv" ]; then
            echo "::error::CSV file does not exist. Skipping commit."
            exit 1
          fi
          echo "CSV file exists. Proceeding to commit."

      - name: Commit new file
        uses: EndBug/add-and-commit@v9
        with:
          add: "gs/SimuladorEletricidade_OF_MN_2025_3.csv"
          message: "Adiciona novo arquivo gerado pelo workflow"
          github_token: ${{ secrets.PAT_TOKEN }}
