name: Run R Script and Commit CSV Teste

on:
  workflow_dispatch:  # Permite execução manual

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      RENV_PATHS_CACHE: ~/.local/share/renv/cache
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2

      - name: Create renv directory if it doesn't exist
        run: mkdir -p renv/library

      - name: Setup cache for R packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/share/renv/cache
            renv/library
          key: renv-cache-${{ runner.os }}-${{ hashFiles('renv.lock') }}
          restore-keys: |
            renv-cache-${{ runner.os }}-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libgit2-dev libx11-dev dbus-x11 net-tools

      - name: Install renv, restore
        run: |
          Rscript -e 'install.packages("renv", repos="https://cran.rstudio.com/")'
          Rscript -e 'renv::activate(); renv::restore(prompt = FALSE)'

      - name: Install Java
        run: sudo apt-get install -y default-jre

      - name: Remove Firefox Snap and Install Dependencies
        run: |
          sudo snap remove firefox || echo "Firefox snap não estava instalado."
          sudo apt-get purge firefox -y
          sudo add-apt-repository -y ppa:mozillateam/ppa
          sudo apt-get update
          sudo apt-get install -y firefox dbus-x11

      - name: Install Correct Geckodriver Version
        run: |
          GECKO_VERSION="0.36.0"
          sudo rm -f /usr/local/bin/geckodriver
          wget -q "https://github.com/mozilla/geckodriver/releases/download/v$GECKO_VERSION/geckodriver-v$GECKO_VERSION-linux64.tar.gz"
          tar -xzf geckodriver-v$GECKO_VERSION-linux64.tar.gz
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/
          sudo chown $(whoami) /usr/local/bin/geckodriver
          geckodriver --version

      - name: Kill any running Firefox
        run: |
          echo "🔪 Encerrando possíveis instâncias travadas do Firefox..."
          pkill -9 firefox || echo "Nenhuma instância do Firefox em execução."

      - name: Start Virtual Display
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          echo "🎥 Display virtual iniciado."
          sleep 5

      - name: Test Firefox Standalone
        run: |
          export DISPLAY=:99
          echo "🌍 Testando Firefox em modo headless..."
          firefox --headless --screenshot && echo "✅ Firefox funcionando!" || echo "❌ Erro ao iniciar Firefox!"

      - name: Start Selenium Server with Logging
        run: |
          export DISPLAY=:99
          export PATH=$PWD:$PATH
          export GECKODRIVER_PATH="/usr/local/bin/geckodriver"
          export MOZ_HEADLESS=1
          
          echo "🔥 Iniciando Selenium Server..."
          java -Dwebdriver.gecko.driver=$GECKODRIVER_PATH \
               -jar selenium-server.jar standalone \
               --port 4444 --host 127.0.0.1 > selenium.log 2>&1 &
          
          sleep 30
          echo "✅ Selenium Server iniciado na porta 4444"

      - name: Check Selenium Server Status
        run: |
          echo "🔍 Verificando se Selenium realmente iniciou..."
          if ! ps aux | grep '[s]elenium-server.jar'; then
            echo "❌ ERRO: O Selenium Server não está a correr!"
            cat selenium.log
            exit 1
          fi

      - name: Check if Selenium port is open
        run: |
          echo "🔍 Verificando portas ativas..."
          if ! netstat -tuln | grep 4444; then
            echo "❌ ERRO: A porta 4444 não está ativa!"
            exit 1
          fi

      - name: Run a simple Selenium test
        run: |
          echo "🟠 Testando criação de sessão no Firefox..."
          curl -X POST http://127.0.0.1:4444/session \
          -H "Content-Type: application/json; charset=utf-8" \
          -d '{
                "capabilities": {
                  "alwaysMatch": {
                    "browserName": "firefox",
                    "moz:firefoxOptions": {
                      "args": ["--headless"]
                    }
                  }
                }
              }' || echo "❌ Erro ao criar sessão do Firefox!"

      - name: Run R script
        run: |
          Rscript -e '
            renv::activate();
            print(.libPaths());
            library(httr);
            print(installed.packages()[,1]);
            print(Sys.getenv("RENV_PATHS_ROOT"));
            source("gs/rscript_teste.R")
          '

      - name: Check if CSV file exists
        run: |
          if [ ! -f "gs/SimuladorEletricidade_OF_MN_2025_2.csv" ]; then
            echo "::error::CSV file does not exist. Skipping commit."
            exit 1
          fi
          echo "CSV file exists. Proceeding to commit."

      - name: Commit new file
        uses: EndBug/add-and-commit@v9
        with:
          add: "gs/SimuladorEletricidade_OF_MN_2025_3.csv"
          message: "Adiciona novo arquivo gerado pelo workflow"
          github_token: ${{ secrets.PAT_TOKEN }}


