name: Verifica novo ficheiro ERSE com Selenium

on:
  schedule:
    - cron: '00 10 * * *'  # todos os dias às 10h UTC (11h em Portugal)
    - cron: '00 16 * * *'  # todos os dias às 16h UTC (17h em Portugal)
  workflow_dispatch:

jobs:
  check-erse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          pip install selenium requests

      - name: Definir variável de ambiente para Chrome
        run: |
          echo "CHROME_BIN=$(which chromium-browser)" >> $GITHUB_ENV

      - name: Executar script de verificação
        env:
          PATH: /usr/bin:$PATH
        run: python3 script/verifica_novo_ficheiro.py

      - name: Commit e push se houver ficheiro novo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add ERSE/*.zip || echo "Nada para adicionar"
          git commit -m "Novo ficheiro ERSE guardado automaticamente" || echo "Sem alterações"
          git push
