name: Run R Script

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2

      - name: Run R script
        run: Rscript gs/rscript.R
