name: Minimal RSelenium + geckodriver Test

on:
  workflow_dispatch:

jobs:
  test-firefox-geckodriver:
    runs-on: ubuntu-latest
    steps:
      - name: Checar repositório (opcional)
        uses: actions/checkout@v4

      - name: Remover Snap e Firefox Snap
        run: |
          sudo snap remove firefox || echo "Snap firefox não estava instalado."
          sudo apt-get purge -y firefox*
      
      - name: Adicionar PPA mozillateam
        run: |
          sudo add-apt-repository -y ppa:mozillateam/ppa
          echo 'Package: firefox*
          Pin: release o=LP-PPA-mozillateam
          Pin-Priority: 1001' | sudo tee /etc/apt/preferences.d/mozillateam-ppa > /dev/null
          sudo apt-get update
          # Instala firefox sem snap
          sudo apt-get install -y firefox
          firefox --version  # Debug: deve exibir algo como "Mozilla Firefox 136.0.2"

      - name: Instalar geckodriver manualmente
        run: |
          GECKO_VERSION="0.36.0"
          wget -q "https://github.com/mozilla/geckodriver/releases/download/v${GECKO_VERSION}/geckodriver-v${GECKO_VERSION}-linux64.tar.gz"
          tar -xzf geckodriver-v${GECKO_VERSION}-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          rm geckodriver-v${GECKO_VERSION}-linux64.tar.gz
          geckodriver --version  # Debug

      - name: Instalar dependências do R e Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y r-base xvfb x11-utils libnss3 libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Subir Xvfb
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          sleep 2
          DISPLAY=:99 xdpyinfo  # checa se subiu; se falhar, falha job

      - name: Subir geckodriver standalone
        run: |
          export DISPLAY=:99
          nohup geckodriver --port 4444 > geckodriver.log 2>&1 &
          sleep 2
          cat geckodriver.log  # ver se subiu OK

      - name: Testar com RSelenium
        run: |
          # Instala RSelenium rapidamente
          Rscript -e 'install.packages("RSelenium", repos="https://cran.rstudio.com")'
          # Testa
          Rscript -e '
            Sys.setenv(DISPLAY=":99")
            library(RSelenium)
            # Conecta no geckodriver:
            remDr <- remoteDriver(remoteServerAddr="127.0.0.1", port=4444L, browserName="firefox")
            remDr$open()
            remDr$navigate("https://www.google.com")
            Sys.sleep(5)
            url <- remDr$getCurrentUrl()
            cat("URL atual:", url, "\n")
            
            ps <- remDr$getPageSource()[[1]]
            cat("Snippet da page source:\n", substring(ps,1,200), "\n")
            
            remDr$close()
          '
          echo "=== Conteúdo do geckodriver.log ==="
          cat geckodriver.log
