name: "Teste minimalista geckodriver + Firefox"

on:
  workflow_dispatch:

jobs:
  test-firefox:
    runs-on: ubuntu-latest
    steps:
    - name: Instalar libs
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libnss3 libcurl4-openssl-dev libssl-dev libxml2-dev wget

    - name: Instalar Firefox sem snap
      run: |
        sudo snap remove firefox || true
        sudo apt-get purge -y firefox*
        sudo add-apt-repository -y ppa:mozillateam/ppa
        sudo apt-get update
        sudo apt-get install -y firefox
        firefox --version

    - name: Instalar geckodriver
      run: |
        wget https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz
        tar -xzf geckodriver-v0.36.0-linux64.tar.gz
        sudo mv geckodriver /usr/local/bin/
        geckodriver --version

    - name: Subir Xvfb
      run: |
        Xvfb :99 -screen 0 1920x1080x24 &
        sleep 3
        xdpyinfo -display :99

    - name: Rodar geckodriver standalone
      run: |
        export DISPLAY=:99
        nohup geckodriver --port 4444 --log debug > geckodriver.log 2>&1 &
        sleep 3
        cat geckodriver.log

    - name: Testar com RSelenium
      run: |
        Rscript -e 'install.packages("RSelenium", repos="https://cran.rstudio.com")'
        Rscript -e '
          library(RSelenium)
          Sys.setenv(DISPLAY=":99")
          remDr <- remoteDriver(remoteServerAddr="127.0.0.1", port=4444L, browserName="firefox")
          remDr$open()
          remDr$navigate("https://www.google.com")
          Sys.sleep(5)
          cat("URL atual:", remDr$getCurrentUrl(), "\n")
          cat("PageSource snippet:\n", substring(remDr$getPageSource()[[1]],1,200), "\n")
          remDr$close()
        '
        cat geckodriver.log
