name: Selenium Test Minimal

on:
  workflow_dispatch: {}

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      # 1) Fazer checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Configurar R
      - name: Instalar R via setup-r
        uses: r-lib/actions/setup-r@v2
        with:
          # Por padrão, instala R mais recente disponível.
          # Se quiser uma versão específica, defina: r-version: '4.2.2'
          use-public-rspm: true

      # 3) Instalar libs do sistema
      - name: Instalar pacotes do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            xvfb libx11-dev libssl-dev libxml2-dev \
            libcurl4-openssl-dev wget unzip

      # 4) Instalar Firefox sem Snap
      - name: Instalar Firefox
        run: |
          sudo snap remove firefox || echo "snap firefox não estava instalado"
          sudo apt-get purge -y firefox*
          sudo add-apt-repository -y ppa:mozillateam/ppa
          echo 'Package: firefox*
          Pin: release o=LP-PPA-mozillateam
          Pin-Priority: 1001' | sudo tee /etc/apt/preferences.d/mozillateam-ppa > /dev/null
          sudo apt-get update
          sudo apt-get install -y --allow-downgrades firefox
          firefox --version

      # 5) Instalar geckodriver
      - name: Instalar geckodriver
        run: |
          GECKO_VERSION="0.36.0"
          wget "https://github.com/mozilla/geckodriver/releases/download/v$GECKO_VERSION/geckodriver-v$GECKO_VERSION-linux64.tar.gz"
          tar -xzf geckodriver-v$GECKO_VERSION-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          rm geckodriver-v$GECKO_VERSION-linux64.tar.gz
          geckodriver --version

      # 6) Subir Xvfb
      - name: Iniciar Xvfb
        run: |
          nohup Xvfb :99 -screen 0 1920x1080x24 &

      # 7) Baixar Selenium Server
      - name: Baixar Selenium
        run: |
          wget -q "https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.29.0/selenium-server-4.29.0.jar" -O selenium-server.jar

      # 8) Subir Selenium Server (standalone)
      - name: Iniciar Selenium
        run: |
          export DISPLAY=:99
          nohup java -jar selenium-server.jar standalone --port 4444 --host 127.0.0.1 \
            >selenium.log 2>&1 &
          sleep 15
          echo "Selenium Iniciado"

      # 9) Instalar pacotes R que faltam
      - name: Instalar pacotes R
        run: |
          Rscript -e 'install.packages(c("RSelenium", "jsonlite"), repos="https://cran.rstudio.com")'

      # 10) Testar RSelenium Mínimo
      - name: Teste RSelenium
        run: |
          export DISPLAY=:99
          Rscript -e '
            library(RSelenium)
            remDr <- remoteDriver(
              remoteServerAddr = "127.0.0.1",
              port = 4444,
              browserName = "firefox"
            )
            message("-> Abrindo Firefox via Selenium...")
            remDr$open()
            remDr$navigate("https://www.google.com")
            Sys.sleep(3)
            current <- remDr$getCurrentUrl()
            message("URL atual: ", current)
            remDr$close()
          '

          '

