name: Selenium Test Minimal

on:
  workflow_dispatch: {}

jobs:
  selenium-rselenium:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - name: Instalar deps do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb firefox
          # geckodriver...
          wget https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz
          tar -xzf geckodriver-v0.36.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          geckodriver --version

      - name: Subir Xvfb
        run: nohup Xvfb :99 -screen 0 1920x1080x24 &

      - name: Baixar Selenium
        run: wget https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.29.0/selenium-server-4.29.0.jar

      - name: Iniciar Selenium
        run: |
          export PATH="/usr/local/bin:$PATH"
          export DISPLAY=:99
          nohup java -Dwebdriver.gecko.driver=/usr/local/bin/geckodriver \
            -jar selenium-server-4.29.0.jar standalone \
            --port 4444 --host 127.0.0.1 >selenium.log 2>&1 &
          sleep 10
          echo "Selenium subiu"

      - name: Instalar pacotes R
        run: |
          Rscript -e 'install.packages("RSelenium", repos="https://cran.rstudio.com")'

      - name: Testar RSelenium
        run: |
          export DISPLAY=:99
          Rscript -e '
            library(RSelenium)
            remDr <- remoteDriver(
              remoteServerAddr="127.0.0.1",
              port=4444,
              browserName="firefox"
            )
            message("Abrindo Firefox via Selenium...")
            remDr$open()
            remDr$navigate("https://www.google.com")
            Sys.sleep(3)
            cur <- remDr$getCurrentUrl()
            message("URL atual: ", cur)
            remDr$close()
          '
