name: Test Write in gs Directory

on:
  workflow_dispatch:

jobs:
  test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create test file in gs directory
        run: |
          echo "Teste de escrita com PAT" > gs/test_file.txt

      - name: Commit test file
        uses: EndBug/add-and-commit@v9
        with:
          add: "gs/test_file.txt"
          message: "Teste: adiciona arquivo de teste no diretório gs"
          github_token: ${{ secrets.PAT_TOKEN }}
