name: RSelenium Firefox Headless (final fix)

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb openjdk-11-jre-headless wget libdbus-glib-1-2 libcurl4-openssl-dev libssl-dev libxml2-dev net-tools

      - name: Instalar Firefox oficial
        run: |
          wget -O firefox.tar.bz2 "https://ftp.mozilla.org/pub/firefox/releases/118.0/linux-x86_64/en-US/firefox-118.0.tar.bz2"
          sudo tar -xjf firefox.tar.bz2 -C /opt
          sudo ln -sf /opt/firefox/firefox /usr/bin/firefox
          firefox --version

      - name: Instalar Geckodriver
        run: |
          wget -q -O geckodriver.tar.gz "https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz"
          sudo tar -xzf geckodriver.tar.gz -C /usr/local/bin/
          sudo chmod +x /usr/local/bin/geckodriver
          geckodriver --version

      - name: Baixar Selenium Server
        run: |
          wget -O selenium-server.jar "https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.29.0/selenium-server-4.29.0.jar"

      - name: Iniciar Xvfb e Selenium Server (corrigido definitivamente)
        run: |
          sudo pkill -9 Xvfb || true
          sudo rm -rf /tmp/.X99-lock /tmp/.X11-unix/X99
          Xvfb :99 -ac -screen 0 1280x1024x24 &
          sleep 5
          echo "DISPLAY=:99" >> $GITHUB_ENV

          sudo pkill -9 -f selenium-server || true
          nohup java \
            -Dwebdriver.gecko.driver=/usr/local/bin/geckodriver \
            -Dwebdriver.firefox.bin=/opt/firefox/firefox \
            -jar selenium-server.jar standalone \
            --host 127.0.0.1 --port 4444 \
            --selenium-manager false \
            > selenium.log 2>&1 &

          sleep 10
          netstat -tuln | grep '127.0.0.1:4444' || (cat selenium.log && exit 1)

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.3'

      - name: Instalar RSelenium
        run: |
          Rscript -e 'install.packages("RSelenium", repos="https://cloud.r-project.org")'

      - name: Teste RSelenium com Firefox headless (definitivo com diagnóstico)
        env:
          DISPLAY: :99
        run: |
          Rscript -e '
            library(RSelenium)
            remDr <- remoteDriver(
              remoteServerAddr = "127.0.0.1",
              port = 4444L,
              browserName = "firefox",
              extraCapabilities = list(
                "moz:firefoxOptions" = list(args = list("--headless", "--no-sandbox"))
              )
            )
            remDr$open(silent = FALSE)
            
            if (is.null(remDr$sessionid)) {
              stop("Falha ao abrir sessão no Selenium Server. Verifique instalação do Firefox e Geckodriver.")
            }

            remDr$navigate("https://www.google.com")
            Sys.sleep(5)
            current_url <- remDr$getCurrentUrl()[[1]]
            page_title <- remDr$getTitle()[[1]]
            cat("URL atual:", current_url, "\n")
            cat("Título:", page_title, "\n")
            if (is.na(current_url) || current_url == "") {
              stop("URL está vazia ou NA - falhando o job")
            }
            remDr$close()
          '

      - name: Exibir log Selenium (em caso de falha)
        if: always()
        run: cat selenium.log
