name: Teste Selenium (com placeholders para Chrome/Edge)

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1) Instalar pacotes de sistema (libcurl4-openssl-dev, etc.)
      - name: Install system dependencies
        run: |
          sudo apt-get update
          # libcurl4-openssl-dev é crucial para compilar o pacote 'curl' do R
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libgit2-dev

      # 2) Instalar R
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.3'  # ou outra versão

      # 3) (Opcional) Instalar e restaurar renv
      - name: Setup renv
        uses: r-lib/actions/setup-renv@v2

      # 4) Restaura pacotes do renv (que agora vai conseguir compilar 'curl')
      #    ou instala manualmente
      - name: Restore renv
        run: |
          Rscript -e 'renv::restore()'

      - name: Setup Firefox and Dependencies
        run: |
          sudo add-apt-repository -y ppa:mozillateam/ppa
          echo 'Package: *
          Pin: release o=LP-PPA-mozillateam
          Pin-Priority: 1001

          Package: firefox
          Pin: version 1:1snap*
          Pin-Priority: -1' | sudo tee /etc/apt/preferences.d/mozilla-firefox
          sudo apt-get update
          sudo snap remove firefox || true
          sudo apt-get install -y firefox xvfb dbus-x11 openjdk-11-jre
          GECKO_VER="0.36.0"
          wget -q https://github.com/mozilla/geckodriver/releases/download/v$GECKO_VER/geckodriver-v${GECKO_VER}-linux64.tar.gz
          tar -xzf geckodriver-v${GECKO_VER}-linux64.tar.gz
          sudo mv geckodriver /usr/bin/ && sudo chmod +x /usr/bin/geckodriver
      - name: Launch Xvfb
        run: |
          Xvfb :99 -ac -screen 0 1920x1080x24 &
          sudo service dbus start
          echo "DISPLAY=:99" >> $GITHUB_ENV
      - name: Start Selenium Server
        run: |
          wget -q https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.29.0/selenium-server-4.29.0.jar
          nohup java -Dwebdriver.gecko.driver=/usr/bin/geckodriver -jar selenium-server-4.29.0.jar standalone > selenium.log 2>&1 &
          sleep 5
      - name: Run RSelenium script
        run: |
          Rscript -e '
            library(RSelenium) 
            # Conecta ao Selenium Server rodando em localhost:4444
            remDr <- remoteDriver(browserName = "firefox", port = 4444)
            remDr$open()  # abre uma instância do Firefox no Xvfb
            remDr$navigate("https://www.google.com")  # navega para a página do Google
            # Captura dados da página
            current_url <- remDr$getCurrentUrl()[[1]]
            title <- remDr$getTitle()[[1]]
            page_html <- remDr$getPageSource()[[1]]
            cat("URL atual:", current_url, "\n")
            cat("Título da página:", title, "\n")
            cat("Trecho do HTML:", substr(page_html, 1, 100), "...\n")
            remDr$close()  # fecha o browser
          '
      - name: Show Selenium log
        if: ${{ always() }}
        run: cat selenium.log
