name: RSelenium Firefox Test (Corrigido Final)

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb openjdk-11-jre-headless wget libdbus-glib-1-2 libcurl4-openssl-dev libssl-dev libxml2-dev net-tools

      - name: Instalar Firefox (118.0)
        run: |
          wget -O firefox.tar.bz2 "https://ftp.mozilla.org/pub/firefox/releases/118.0/linux-x86_64/en-US/firefox-118.0.tar.bz2"
          tar -xjf firefox.tar.bz2
          sudo mv firefox /opt/firefox
          sudo ln -sf /opt/firefox/firefox /usr/bin/firefox
          firefox --version

      - name: Instalar Geckodriver (0.36.0)
        run: |
          wget -q -O geckodriver.tar.gz "https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz"
          tar -xzf geckodriver.tar.gz
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/
          geckodriver --version

      - name: Baixar Selenium Server (4.29.0)
        run: |
          wget -O selenium-server.jar "https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.29.0/selenium-server-4.29.0.jar"

      - name: Iniciar Xvfb e Selenium Server (Firefox e Geckodriver explícitos)
        run: |
          sudo pkill -9 Xvfb || true
          sudo rm -rf /tmp/.X99-lock /tmp/.X11-unix/X99
          Xvfb :99 -screen 0 1280x1024x24 &
          sleep 5
          echo "DISPLAY=:99" >> $GITHUB_ENV

          sudo pkill -9 -f selenium-server || true
          nohup java \
            -Dwebdriver.gecko.driver=/usr/local/bin/geckodriver \
            -Dwebdriver.firefox.bin=/opt/firefox/firefox \
            -jar selenium-server.jar standalone \
            --host 127.0.0.1 --port 4444 \
            > selenium.log 2>&1 &

          sleep 10
          netstat -tuln | grep '127.0.0.1:4444' || (cat selenium.log && exit 1)

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.3'

      - name: Instalar RSelenium
        run: |
          Rscript -e 'install.packages("RSelenium", repos="https://cloud.r-project.org")'

      - name: Executar teste RSelenium
        env:
          DISPLAY: :99
        run: |
          Rscript -e '
            library(RSelenium)
            remDr <- remoteDriver(
              remoteServerAddr = "127.0.0.1",
              port = 4444L,
              browserName = "firefox",
              extraCapabilities = list(
                "moz:firefoxOptions" = list(args = list("--headless", "--no-sandbox"))
              )
            )
            remDr$open()
            remDr$navigate("https://www.google.com")
            Sys.sleep(5)
            current_url <- remDr$getCurrentUrl()[[1]]
            page_title <- remDr$getTitle()[[1]]
            cat("URL atual:", current_url, "\n")
            cat("Título:", page_title, "\n")
            if (is.na(current_url) || current_url == "") {
              stop("URL está vazia ou NA - falhando o job")
            }
            remDr$close()
          '

      - name: Exibir log Selenium (Diagnóstico)
        if: always()
        run: cat selenium.log
