name: RSelenium Firefox Test

on:
  workflow_dispatch:

jobs:
  test-rselenium:
    runs-on: ubuntu-latest
    env:
      DISPLAY: :99
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install Firefox (via PPA) and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:mozillateam/ppa
          # Give PPA priority over Ubuntu repo to avoid Snap package
          echo -e "Package: firefox*\nPin: release o=LP-PPA-mozillateam\nPin-Priority: 1001\nPackage: firefox*\nPin: release o=Ubuntu\nPin-Priority: -1" | sudo tee /etc/apt/preferences.d/99firefox
          sudo apt-get update
          sudo apt-get install -y firefox xvfb libcurl4-openssl-dev libssl-dev libxml2-dev default-jre wget

      - name: Install Geckodriver 0.36.0
        run: |
          wget -q https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz
          tar -xzf geckodriver-v0.36.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/geckodriver

      - name: Install R packages (RSelenium and curl)
        run: Rscript -e 'install.packages(c("RSelenium", "curl"), repos="https://cloud.r-project.org")'

      - name: Start Xvfb
        run: Xvfb :99 -ac -screen 0 1280x1024x16 > /dev/null 2>&1 &

      - name: Start Selenium Server (v4.29.0)
        run: |
          wget -q https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.29.0/selenium-server-4.29.0.jar
          java -jar selenium-server-4.29.0.jar > selenium.log 2>&1 &

      - name: Run RSelenium test
        run: |
          Rscript -e 'library(RSelenium); remDr <- remoteDriver(browserName="firefox", port=4444L); remDr$open(); remDr$navigate("https://www.google.com"); url <- remDr$getCurrentUrl()[[1]]; title <- remDr$getTitle()[[1]]; cat("URL:", url, "\n"); cat("Title:", title, "\n"); if (is.null(url) || url == "" || is.na(url)) { stop("URL is empty or NA") }; remDr$close();'

      - name: Display Selenium log
        if: always()
        run: |
          echo "------ Selenium Server log ------"
          cat selenium.log
