name: RSelenium Headless Firefox Test

on:
  workflow_dispatch:

jobs:
  test-rselenium:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libgit2-dev \
            xvfb \
            dbus-x11 \
            openjdk-17-jre \
            firefox

      - name: Install geckodriver manually
        run: |
          GECKO_VER="0.36.0"
          wget -q https://github.com/mozilla/geckodriver/releases/download/v$GECKO_VER/geckodriver-v${GECKO_VER}-linux64.tar.gz
          tar -xzf geckodriver-v${GECKO_VER}-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/geckodriver
          geckodriver --version

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.3'

      - name: Setup renv
        uses: r-lib/actions/setup-renv@v2

      - name: Restore renv packages
        run: |
          Rscript -e 'renv::restore(prompt = FALSE)'

      - name: Install RSelenium if needed (just in case)
        run: |
          Rscript -e 'if (!requireNamespace("RSelenium", quietly=TRUE)) install.packages("RSelenium", repos="https://cloud.r-project.org")'

      - name: Start Xvfb
        run: |
          Xvfb :99 -ac -screen 0 1920x1080x24 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Download Selenium Server
        run: |
          wget -q https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.29.0/selenium-server-4.29.0.jar -O selenium-server.jar

      - name: Start Selenium (firefox-only)
        run: |
          echo "DISPLAY is $DISPLAY"
          nohup java \
            -Dwebdriver.gecko.driver=/usr/local/bin/geckodriver \
            -jar selenium-server.jar standalone \
            --port 4444 --host 127.0.0.1 \
            --selenium-manager false \
            --drivers firefox \
            > selenium.log 2>&1 &
          sleep 10
          echo "Selenium started."
          ps aux | grep '[s]elenium' || (echo "Selenium not running!" && cat selenium.log && exit 1)
          netstat -tuln | grep 4444 || (echo "Port 4444 not listening!" && cat selenium.log && exit 1)

      - name: Run RSelenium test
        run: |
          Rscript - <<'RSCRIPT'
            library(RSelenium)
            remDr <- remoteDriver(browserName = "firefox", port = 4444L)
            remDr$open()
            remDr$navigate("https://www.google.com")
            Sys.sleep(3)
            page_title <- remDr$getTitle()[[1]]
            page_url <- remDr$getCurrentUrl()[[1]]
            cat("Page Title:", page_title, "\n")
            cat("Page URL:", page_url, "\n")
            if (is.na(page_url) || page_url == "") {
              stop("Failed to retrieve page URL")
            }
            remDr$close()
          RSCRIPT

      - name: Show Selenium logs
        if: always()
        run: cat selenium.log
